#!/bin/bash
#SBATCH -J polymer_tm_sim
#SBATCH -p cpu8562y
#SBATCH -N 1
#SBATCH -n 32
#SBATCH --mem=64G
#SBATCH -o %j.out
#SBATCH -e %j.err

module purge
#module load openmpi/4.1.1
module load gcc/10.2.0
module load lammps/22Jul2025
module load gsl/2.7
source  /fs0/software/intel/2022.2/setvars.sh
echo "Starting LAMMPS run on $SLURM_NTASKS cores using cluster module..."

mpirun -np $SLURM_NTASKS /fs0/software/lammps/lammps-22-2025/bin/lmp_mpi -in in2.txt
